default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pai
  password: tigers
  host: db

development:
  <<: *default
  database: pai_owarai_dev

test:
  <<: *default
  database: pai_owarai_test

production:
  <<: *default
  database: pai_owarai_production
  username: pai_owarai
  password: <%= ENV["PAI_OWARAI_DATABASE_PASSWORD"] %>
